### ISSUE TITLE
You are my saver.. thanks

### ISSUE THREAD

**Issue by DONGILBAE** [Seithan/EasyNextionLibrary#10]
Hey !!! Guy. really you are my saver.. 
I had some problem esp32 connect nextion. 
even follow nextion ITEADLIB... it is pretty has a lot of issues.  and unstable.
 So, I was thinking about giving up this product.
There were many cases where it went well and suddenly stopped working,
Sometimes, communication was impossible at all.
By the way, I found your documentation and this helped me a lot with the project I was trying to do.
So, it seems that I once again gained hope for development.
First of all, I really really appreciate your efforts. Thanks
ESP32 work well and No problem. 
I tested whole day and night.

**Comment by Seithan** [comment]
Hello,

The process of testing is very important and it is great to have feedback from users that have tested the library. 
ESP32 is a very special MCU and thanks to you, we know that it is working well with the library. Despite having run some tests myself, now it is even more certain that the library has been tested from both of us.

Thank you again for your feedback :)
