### ISSUE TITLE
Change value of multiple numbers

### ISSUE THREAD

**Issue by gtetil** [Seithan/EasyNextionLibrary#16]
First off, I'm very impressed with your library.  It is the by far the best Nextion library I have used so far.  Unfortunately, I'm experiencing a very elementary problem.  I have 2 numbers on the Nextion display (on the same page).  

When I run these two lines, n0 updates as expected:

`myNex.writeNum("n0.val", nex_temp);`
`myNex.writeNum("n0.val", nex_temp);`

When I run these two lines, neither n0 or n1 update:

`myNex.writeNum("n0.val", nex_temp);`
`myNex.writeNum("n1.val", nex_temp);`

When I run these two lines, n2 updates as expected:

`myNex.writeNum("n2.val", nex_temp);`
`myNex.writeNum("n2.val", nex_temp);`

I seemingly can't write to more than one number.

**Comment by gtetil** [comment]
Sorry.  Figured it out.

**Comment by amaral-roberto** [comment]
Same to me.
