### ISSUE TITLE
HardwareSerial selection

### ISSUE THREAD

**Issue by Zefram88** [Seithan/EasyNextionLibrary#22]
Hi, as in title, i was wondering if there's any possibility to switch to other HardwareSerial ports and map pins on it, i'm using an ESP32 and would be nice to try Hardware Serial 2 (with pin 32 and 33) because i'm already using the first serial as monitor for testing on usb.

Thanks

**Comment by Seithan** [comment]
Hello
Try Serial2 in place of Serial
````Cpp
EasyNex myNex(Serial); // Create an object of EasyNex class with the name < myNex > 
                       // Set as parameter the Hardware Serial you are going to use
````

**Comment by dlaps007** [comment]
Hello, this method works for me using Serial2 with ESP32.
I use the Serial to print when debugging.
