### ISSUE TITLE
Collect sleep information

### ISSUE THREAD

**Issue by D-Salmon** [Seithan/EasyNextionLibrary#25]
Hi,
I've discovered your awesome library and I have a request.
To stop sending commands for refreshing values to Nextion, I'd like to be informed when Nextion is in sleep mode.
I've seen that the display sends 0x86 but I haven't found how to collect it wih your library

**Comment by ricreis394** [comment]
I'm interested in this. Subscribing...

**Comment by Seithan** [comment]
Hello,

How are you planning to make the Nextion go to sleep mode? With what way?

**Comment by D-Salmon** [comment]
Hi Seithan
I only configure in Nextion
thsp=15
thup=1
When the display enters in sleep mode after15 seconds, it sends 86 FF FF FF
It sends 87 FF FF FF when it wakes up
If I could read these informations, I would stop communication beetween Arduino and Nextion for a while

**Comment by Seithan** [comment]
Hello
I made some modifications. I will attach the files.
You have to replace those two files in the library's folder and then give it a try.
A new public variable is there
`boolean sleep` that is `true` when a `86 FF FF FF` is received and `false` when `87 FF FF FF`
````Cpp
    if(myNex.sleep == true){
    myNex.writeStr("t1.txt", "sleep = true");
  }else if(myNex.sleep == false){
    myNex.writeStr("t1.txt", "sleep = false");    
  }
````
[EasyNextionLibrary.zip](https://github.com/Seithan/EasyNextionLibrary/files/6015741/EasyNextionLibrary.zip)

**Comment by Seithan** [comment]
Hello,

I made some changes in these files. I removed some debug commands that I forgot.

[EasyNextionLibrary.zip](https://github.com/Seithan/EasyNextionLibrary/files/6018456/EasyNextionLibrary.zip)

**Comment by D-Salmon** [comment]
Hello Seithan
Fantastic, exactly what I needed.
Thank you so much for your job

**Comment by Seithan** [comment]
Have you tried them?

Please give me a feedback if the files are working, so I can change them in a future release.

If you do not need anything else from this issue, close it and give a star to the library on the top right corner :)

**Comment by D-Salmon** [comment]
Hi Seithan,
Of course I've tried and it works like a charm.

**Comment by ricreis394** [comment]
This feature was already released?

**Comment by Seithan** [comment]
Hello @ricreis394,
I have not released this feature yet, as I want to see some other modifications.

Do you need the release now or can you do it with the two attached files?
