### ISSUE TITLE
ESP32 serial communication issue with Nextion

### ISSUE THREAD

**Issue by digitalbird01** [Seithan/EasyNextionLibrary#26]
I am having trouble writing data from ESP32 serial2 to Nextion. I can receive hits from the Nextion but don't seem to be able to write anything is this anything you have come across?

**Comment by Seithan** [comment]
Hello
You can check this Issue and pleace let me know if your problem is solved.
#24

**Comment by digitalbird01** [comment]
Hi Seithan
It works!!!! Many thanks for the help I have been pulling my hair out for
two days on this basic issue. I was powering the nextion from a separate
supply.
No common earth!  As soon as I powered both the nextion and the ESP32 from
two USB ports on the same system everything worked. Know I can get on
with the hard part.😀

**Comment by Seithan** [comment]
Hello,

I believe you do not need this issue no more. You are free to close it, but before you do that, go to the top right corner of the GitHub page and star the library :)

**Comment by digitalbird01** [comment]
Awesome, thanks!
