### ISSUE TITLE
Read data from EEPROM of nextion to arduino and store as float or veriable.

### ISSUE THREAD

**Issue by fani625** [Seithan/EasyNextionLibrary#29]
Thanks for this great  work it help me alot and save my time.

I am working on a project where I store all variable and float reading on nextion EEPROM. No I want to read that data over the serial with below command so every time when run the setup it will store all variable on arduino from nextion. because I am facing the issue when I read directly from nextion with "myNex.read Number" it missed first variable .

`rept 30,20 // sends 20 bytes from EEPROM addresses 30 to 49 to serial// byte of data is not ASCII text of byte value, but raw byte `

Thanks,

**Comment by Seithan** [comment]
Hello fani,

I do not have much experience with the Nextion EEPROM. Why don't you use the Arduino's EEPROM instead?
