### ISSUE TITLE
sendind special characteres out uf ascii encode

### ISSUE THREAD

**Issue by medusadecampo** [Seithan/EasyNextionLibrary#30]
Hello is posible to send special characteres in the writestr funcion ,like  " ó é"
Now i am receiving in the display erroneus characteres .
thank you.

**Comment by Seithan** [comment]
Hello
Please check out Nextion Editor Guide
https://nextion.tech/editor_guide/

"

> Character Encoding is default iso-8859-1. Select from the character encodings that make sense for your HMI project to best display your local character sets. There are a selection of single byte and double byte character sets available.
> 
> Currently supported Character encodings include:
> ASCII, ISO-8859-X (1,2,3,4,5,6,7,8,9,11,13,15), UTF8,
> GB2312, BIG5, KS_C_5601-1987, Big5, Shift-JIS, Koi8-r,
> Windows 874, 1255, 1256, 1257, and 1258
> 
> Note: An encoding is a character mapping of value to character. Computer systems and MCUs use numeric values and not characters. A byte numeric value 0x41 in single byte ASCII encoding will reference the character A. Your MCU will not send A, it sends byte 0x41 (which in many cases maybe mapped to the letter A), but does not explicitly mean 0x41 renders A in every encoding. A Byte value of 0xC4 can map to different characters in different encodings, or even be undefined (mapping to no character). While modern computers can do translations between many encodings, your MCU will likely not. It is useful to research the encoding you are planning to use.
"
