### ISSUE TITLE
How from arduino, read nextion dataRecord ?

### ISSUE THREAD

**Issue by kang2k10** [Seithan/EasyNextionLibrary#31]
Hello.
How from arduino, read nextion dataRecord ?

**Comment by Seithan** [comment]
Hello,
I have not found an easy way to make this.
But for sure you can store into a string component (t0.txt) the selected line of the dataRecord. After that, you can read from Arduino t0.txt as a string.
Here is a video for dataRecord . You can see how to store a dataRecord to txt
[https://www.youtube.com/watch?v=he1_YCaMacc](url)
