### ISSUE TITLE
How to change the picture on nextion?

### ISSUE THREAD

**Issue by nodoubtman** [Seithan/EasyNextionLibrary#32]
Can we change the picture on the nextion display?

And how?

Thanks.
Marc.

**Comment by Seithan** [comment]
Hello,
Could you be more specific?
And please read the documentation as you might find what you are looking for.

**Comment by nodoubtman** [comment]
Hello, i mean how to change Picture ( p0, p1, p2, etc...)

It's not written in the docs

thanks.
Marc.

**Comment by Seithan** [comment]
Hello,
In picture components, there is a numeric attribute "pic", where the value is the id of the picture.
You can use the writeNum() function, and as the documentation says: 
"Description: For writing numbers in numeric attributes in components of any kind (variables, textboxes, etc.)."
[https://github.com/Seithan/EasyNextionLibrary#function-writenum](url)
