### ISSUE TITLE
FR Reed Touch Coordinates

### ISSUE THREAD

**Issue by Terixxx** [Seithan/EasyNextionLibrary#34]
Thanks for the great work in this library and i have to ask for help. In my project i need to handle touch coordinates enabled with command: sendxy=1
The returned data is: 
67 (02 DA)x (00 D2)y (01 or 00 pressed and released) FF FF FF 
Could you please help me to implement that future in the existing library class.

I try to put this code but not working correctly
`
// public variables
 uint16_t touchX;
 uint16_t touchY;
boolean EasyNex::NextionListen(){
.
.
.
if(_start_char == 'g'){            // And when we find the character #
      for(int i = 0; i < 5; i++){   // If the command is 'R' (read Number) go on read the number and store them in the numeric buffer 
		        _numericBuffer[i] = _serial->read();
	        }
          delay(3);
          
          
          int _checkNextByte = _serial->peek();  // We take the four bytes. Are they the correct ones we expected?
                                                 // Or we have some unwanted data (garbage data) that comes to the Serial.
                                                 // To ensure that, we check what is the next byte on Serial.
                                                 // If everything is as it should be, the next byte must be a '#',
                                                 // which means a command is following, or the Serial must be empty.
                                                 // In this way, we lower the chances of having a bad reading.
                                                 // But nothing is completely unavoidable.
          
          
          
          if(_checkNextByte == 35 || _checkNextByte == -1){ // Check the next byte. 35 = '#',  -1 = empty Serial
            
            // We can continue with the little endian conversion
            _numberValue = _numericBuffer[4];
            _numberValue <<= 8;
            if (_numberValue == 1){
              isPressed = true;
            }else{
              isPressed = false;
            }
            _numberValue = _numericBuffer[3];
            _numberValue <<= 8;
            _numberValue |= _numericBuffer[2];
            _numberValue <<= 8;
            touchX = _numberValue;
            _numberValue = _numericBuffer[1];
            _numberValue <<= 8;
            _numberValue |= _numericBuffer[0];
            touchY = _numberValue; 
            _waitingForNumber = true;         // Means that we found the correct number and we are going to send it         
            
          }else{  // Else if the Serial is not empty, and the next byte is not 35, then this data doesn't belong to us
            _tmr1 = millis();
            while(_checkNextByte != 35){  // So we send them back where they came from.
              _serial->read();
              _checkNextByte = _serial->peek();
              if((millis() - _tmr1) > 5UL){ 
                break;
              }
            }
            _waitingForNumber = true;     // means that a readNumber command found and we have the number stored
            _numberValue = 777777;        // The false return value of bad reading.
            return _numberValue;
          }
	}
      if(_start_char == '#'){            // And when we find the character #
      _len = _serial->read();          // Create local variable (len) / read and store the value of the second byte
                                       // <len> is the lenght (number of bytes following) 
      _tmr1 = millis();
      _cmdFound = true;
      
      while(_serial->available() < _len){     // Waiting for all the bytes that we declare with <len> to arrive              
        if((millis() - _tmr1) > 100UL){         // Waiting... But not forever...... 
          _cmdFound = false;                  // tmr_1 a timer to avoid the stack in the while loop if there is not any bytes on _serial
          break;                            
        }                                     
      }                                   
      if(_cmdFound == true){                  // So..., A command is found (bytes in _serial buffer egual more than len)
        _cmd1 = _serial->read();              // Read and store the next byte. This is the command group
        readCommand();                        // We call the readCommand(), 
                                              // in which we read, seperate and execute the commands
			}
		}
	}
  return _cmdFound;
}

`

**Comment by Seithan** [comment]
Hello @Terixxx 

Try those two files I attached here and replace the originals with them.

You can call the public variables sendX and sendY by writing 
```Cpp
int x = myNex.sendX;
int y = myNex.sendY;
````
Also, for the Press Event
```Cpp
int event = myNex.pressRelease0x67;
```

[EasyNextionLibrary0x67_0x86_0x87.zip](https://github.com/Seithan/EasyNextionLibrary/files/7112318/EasyNextionLibrary0x67_0x86_0x87.zip)

**Comment by Terixxx** [comment]
Hello @Seithan

Code works perfect! Thank you very much. Now I'm workng on getting time between press and release touch events but this will be hard task  as I see.
