### ISSUE TITLE
Turkish Characters

### ISSUE THREAD

**Issue by MKucukturkmen** [Seithan/EasyNextionLibrary#38]
Hello I use this func myNex.writeStr and its can not send turkish characters, How can I fix it ? And Thanks for this beautiful library :) it is very simple to use it ı think better than iteadlib.

**Comment by Seithan** [comment]
Hello @MKucukturkmen ,
The characters sent have nothing to do with the library.
You must select the right font on Nextion Editor, that supports turkish characters
