### ISSUE TITLE
#T on triger Serial.println

### ISSUE THREAD

**Issue by puhycz** [Seithan/EasyNextionLibrary#41]
Hello, 

I Use Easy Nextion Library@^1.0.6, baud 115200. Send data to display works ok, but receive (by press button on disple f.e.) not works.

For example in triger0 I have Serial.println("button pressed"), but in terminal from ESP32 print this:

![image](https://user-images.githubusercontent.com/6555850/190625181-e861358a-3fbd-4165-9bab-bb6b83f87a0e.png)

Next messages from terminal ESP32 are ok, but all from triggers it print only #T . 

I dont know why. Plese help me.

Many thaks,

Jan

**Comment by Seithan** [comment]
Try this
````Cpp
void trigger2(){
myNex.writeStr("t0.txt", "P"); //(t0.txt in in same page)
}
````
Serial.println is not a member of the library
