### ISSUE TITLE
Check if is display connected

### ISSUE THREAD

**Issue by puhycz** [Seithan/EasyNextionLibrary#55]
Please how can i test if the display is connected? I need use ESP32 with connected or disconnected HMI display and with same firmware.

Thanks.

**Comment by Seithan** [comment]
You can build a watchdog.
On Nextion use a timmer and every 5sec send a trigger command to mcu
from mcu set a timer to zero every time you receive the command, and check if the timer exceed the 5sec that means that the display is disconnected
