### ISSUE TITLE
Read negative number

### ISSUE THREAD

**Issue by s56jsc** [Seithan/EasyNextionLibrary#56]
How to read negative number from nextion? I have max_p.val type float
If I use P_max_set = myNex.readNumber("max_p.val");
positive work great, but negative I got overflow number

**Comment by Seithan** [comment]
https://github.com/Seithan/EasyNextionLibrary#send-floating-point-numbers-a-number-that-has-a-decimal-point

**Comment by s56jsc** [comment]
Not a problem for sent. But for reading........

**Comment by Seithan** [comment]
You face the same problem with number Attribute?
