### ISSUE TITLE
Where is the zip file on Github

### ISSUE THREAD

**Issue by bossinfo** [Seithan/EasyNextionLibrary#7]
I was trying to download your library from Github but can't find the zip file that you say I should see using the second download method that you specify in your Readme.md file.
Am I missing something?

**Comment by Seithan** [comment]
Hello bossinfo,

To download the .zip file of the library, first, you will need to be at ....Seithan/EasyNextionLibrary page. Then, click on the **Code** option on the top right side.
Finally, click on **Download ZIP**

If you do not have further questions, close this issue :)
